//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateCamera.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.71/ch1/sub/av_stream")]
        public string Cam1 {
            get {
                return ((string)(this["Cam1"]));
            }
            set {
                this["Cam1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.72/ch1/sub/av_stream")]
        public string Cam2 {
            get {
                return ((string)(this["Cam2"]));
            }
            set {
                this["Cam2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.73/ch1/sub/av_stream")]
        public string Cam3 {
            get {
                return ((string)(this["Cam3"]));
            }
            set {
                this["Cam3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.74/ch1/sub/av_stream")]
        public string Cam4 {
            get {
                return ((string)(this["Cam4"]));
            }
            set {
                this["Cam4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.75/ch1/sub/av_stream")]
        public string Cam5 {
            get {
                return ((string)(this["Cam5"]));
            }
            set {
                this["Cam5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.76/ch1/sub/av_stream")]
        public string Cam6 {
            get {
                return ((string)(this["Cam6"]));
            }
            set {
                this["Cam6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.77/ch1/sub/av_stream")]
        public string Cam7 {
            get {
                return ((string)(this["Cam7"]));
            }
            set {
                this["Cam7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.78/ch1/sub/av_stream")]
        public string Cam8 {
            get {
                return ((string)(this["Cam8"]));
            }
            set {
                this["Cam8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.79/ch1/sub/av_stream")]
        public string Cam9 {
            get {
                return ((string)(this["Cam9"]));
            }
            set {
                this["Cam9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.80/ch1/sub/av_stream")]
        public string Cam10 {
            get {
                return ((string)(this["Cam10"]));
            }
            set {
                this["Cam10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.108/ch1/sub/av_stream")]
        public string Cam11 {
            get {
                return ((string)(this["Cam11"]));
            }
            set {
                this["Cam11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.109/ch1/sub/av_stream")]
        public string Cam12 {
            get {
                return ((string)(this["Cam12"]));
            }
            set {
                this["Cam12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.110/ch1/sub/av_stream")]
        public string Cam13 {
            get {
                return ((string)(this["Cam13"]));
            }
            set {
                this["Cam13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://admin:abcd1234@192.168.41.111/ch1/sub/av_stream")]
        public string Cam14 {
            get {
                return ((string)(this["Cam14"]));
            }
            set {
                this["Cam14"] = value;
            }
        }
    }
}
